### ISSUE TITLE
Gem hosting

### ISSUE THREAD

**Issue by logankoester** [squeejee/twitterland#1]
Since github doesn't do gem hosting anymore, can you host this gem somewhere? Preferably http://gemcutter.org/ :-)

Thank you!

**Comment by pengwynn** [comment]
Hey logan, twitterland has been on Gemcutter for quite a while. http://gemcutter.org/gems/twitterland  Are you not able to install using 

```
sudo gem install twitterland
```

**Comment by logankoester** [comment]
Sorry, my mistake - turns out I didn't have gemcutter listed as a source. Thanks for getting back to me!

**Comment by polomasta** [comment]
time to close this one :-)
